apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-app-container
        image: konark111/python-kub-dep
        volumeMounts:
        - name: db-connect
          mountPath: /opt
        ports:
        - containerPort: 8000
          protocol: TCP
      volumes:
      - name: db-connect
        configMap: 
          name: python-cm

